config/routes.rb
PmApp31::Application.routes.draw do
  get "sessions/new"

  resources :users, :only => [:new, :create, :show, :edit, :update]
  resources :sessions, :only => [:new, :create, :destroy]
  resources :ownerships, :only => [:create, :destroy]
  resources :projects do 
    member do
      get 'collaborators'
    end
    resources :stories
    resources :thoughts do
      resources :comments
    end
  end
  
  match '/getstarted',     :to => 'users#new'
  match '/signin',         :to => 'sessions#new'
  match '/signout',        :to => 'sessions#destroy'      
  match '/about',          :to => 'pages#about'
  
  root :to => 'pages#home'
  
end

app/views/pages/about.html.erb
<div class="container">
	</br>
	</br>
	<div class = "span3">
		&nbsp;
	</div>
	<div class = "span6">		
		<div class = "well">
			<div align = "center">		
				<h3>About</h3></br>
				Scratchboard is developed by Neil Kamireddy (<a href="http://www.twitter.com/neilkam/" target= "_blank">@neilkam</a>). It came to exist over a few weekends as a way for Neil to teach himself software development.
			</div>
		</div>
	</div>
	<div class = "span3">
		&nbsp;
	</div>
</div>

app/views/pages/home.html.erb
<!DOCTYPE html>
<html lang="en">
<div class = "container-fluid">
     </br>
     <div class = "hero-unit">
          <h1>Ideate together</h1>
          <p>Scratchboard helps developers, designers, and product managers collaborate to generate product ideas and requirements.</p>
          <p>
          <% if signed_in? %>
               <%= link_to "Get started", current_user, :class => "btn btn-success btn-large" %>
          <% else%>
               <%= link_to "Get started", getstarted_path, :class => "btn btn-success btn-large" %>
          <% end %>
          </p>
     </div>
     <div class = "row-fluid">
          <div class ="span0.5">
               &nbsp;
          </div>
          <div class="span6">
               <h3>Capture ideas now. Fine-tune later.</h3>
               Software development isn't a clean and tidy process. Finely tuned requirements don't just appear - they're a product of
               a series of small ideas and thoughts, iterated and revised over time. Scratchboard is a tool to capture those small ideas (or
               "scratches") when they're fresh and generative. As your project comes into shape, Scratchboard makes it easy to translate your
               scratches to more structured requirement briefs and user stories.
          </div>
          <div class ="span1">
               &nbsp;
          </div>
          <div class="span4">
               <div class="thumbnail">
                     <%= image_tag "hero_new.png" %>
               </div>
          </div>
     </div>
     </br>
     </br>
     </br>
	<div class = "row">
		<div class = "span1">
			&nbsp;
		</div>
	    <ul class="thumbnails">
               <li class ="span3">
                    <div class ="thumbnail">
                         <%= image_tag "feature1_new.png" %>
                    </div>
                    <div align = "center">
                    <h4>Visual project boards</h4>
                    Quickly add scratches to a project and review them later at a glance.
                    </div>
               </li>
               <li class ="span3">
                    <div class ="thumbnail">
                         <%= image_tag "feature3_new.png" %>
                    </div>
                    <div align = "center">
                    <h4>Seamless collaboration</h4>
                    Invite others to your boards and build ideas together with ease.
                    </div>
               </li>
               <li class ="span3">
                    <div class ="thumbnail">
                         <%= image_tag "feature2_new.png" %>
                    </div>
                    <div align = "center">
                    <h4>All types of media</h4>
                    Share photos, docs, links, and more. They all fit right in your project board.
                    </div>
               </li>
        </ul>
		<div class = "span1">
			&nbsp;
		</div>
	</div>
    <div class = "row-fluid">
          <div class ="span1">
               &nbsp;
          </div>
          <div class = "span3">
               <blockquote>
                    <div class = "row-fluid">
                         <div class = "span3">
                              &nbsp;
                         </div>
                         <div class = "span5">
                              <div class = "thumbnail">
                                   <%= image_tag("testimonial.png")%>
                              </div>
                         </div>
                    </div>
               </br>
                    "Scratchboard has made our development team feel a lot smaller. We've kept our agile approach while
                    getting everyone more involved in the ideation process."
                    <small>Mike / Trunk Club</small>
               </blockquote>
          </div>
          <div class = "span1">
               &nbsp;
          </div>
          <div class="span6"><div class = "well">
               <div align = "center">
               </br>
               <h3>Put away the Post-Its. Try Scratchboard.</h3>
               Ideation is too often separated from the agile software development process, isolated offline on post-its and in notebooks.
               Bring your ideas to life with Scratchboard and never lose a good idea again. Also, it's free!
               </div>
               </br>
               <div align = "center">
                    <% if signed_in? %>
                         <%= link_to "Get started", current_user, :class => "btn btn-success btn-large" %>
                    <% else%>
                         <%= link_to "Get started", getstarted_path, :class => "btn btn-success btn-large" %>
                         or <%= link_to "log in", signin_path %>
                    <% end %>
               </div>
               </br>
          </div></div>
    </div>         
</div>
</html>