config/routes.rb
PmApp31::Application.routes.draw do
  get "sessions/new"

  resources :users, :only => [:new, :create, :show, :edit, :update]
  resources :sessions, :only => [:new, :create, :destroy]
  resources :ownerships, :only => [:create, :destroy]
  resources :projects do 
    member do
      get 'collaborators'
    end
    resources :stories
    resources :thoughts do
      resources :comments
    end
  end
  
  match '/getstarted',     :to => 'users#new'
  match '/signin',         :to => 'sessions#new'
  match '/signout',        :to => 'sessions#destroy'      
  match '/about',          :to => 'pages#about'
  
  root :to => 'pages#home'
  
end

app/models/project.rb
class Project < ActiveRecord::Base
  attr_accessible :title, :body, :brief
  has_many :ownerships
  has_many :users, through: :ownerships
  has_many :thoughts
  has_many :stories
  
  validates :title, :presence => true
  validates :body, :presence => true, :length => {:maximum => 140}
  
  default_scope :order => 'projects.updated_at DESC'
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_filter :authenticate
  
  def create
    @project = Project.new(params[:project])
    if @project.save
      @ownership = Ownership.create!(user_id: current_user.id, project_id: @project.id)
      redirect_to @project
    else
      render 'new'
    end
  end
  
  def show
    @project = Project.find(params[:id])
    @title = @project.title
    @thoughts = @project.thoughts
    @stories = @project.stories
    if Ownership.find_by_project_id_and_user_id(@project.id, current_user.id)
      @project
    else
      redirect_to current_user
      flash[:"alert alert-warning"] = "Sorry - you do not have access to that project"
    end
  end
  
  def new
    @project = Project.new if signed_in?
    @user = current_user
    @title = "New project | Scratchboard"
  end
  
  def edit
    @project = Project.find(params[:id])
    @title = @project.title
    @thoughts = @project.thoughts
    if Ownership.find_by_project_id_and_user_id(@project.id, current_user.id)
      @project
    else
      redirect_to current_user
      flash[:"alert alert-warning"] = "Sorry - you do not have access to that project"
    end
  end
  
  def update
    @project = Project.find(params[:id])
    if @project.update_attributes(params[:project])
      redirect_to @project
    else
      redirect_to @project
      flash[:"alert alert-warning"] = "Sorry - there was a problem saving your edit"
    end
  end
  
  def collaborators
    @users = User.all
    @project = Project.find(params[:id])
    @title = 'Project Collaborators'
    if Ownership.find_by_project_id_and_user_id(@project.id, current_user.id)
      collaborators_project_path(@project)
    else
      redirect_to current_user
      flash[:"alert alert-warning"] = "Sorry - you do not have access to that project"
    end
  end

  def destroy
  end
end

app/views/projects/_project.html.erb
<!DOCTYPE html>
<html>
	<ul class="nav nav-pills nav-stacked">
		<li class = "active">
	    	<%= link_to project.title, project_path(project.id) %>
	  	</li>
	</ul>
</html>

app/views/projects/collaborators.html.erb
<!DOCTYPE html>
<html>
<div class = "container">
	</br>
	</br>
	<div class = "span4">
		&nbsp;
	</div>	
	<div class = "span4">
		<%= link_to "<< Back to Project", project_path(@project) %>
		</br>
		</br>
		<div class = "well">
			<div align = "center" >
				<h3>Manage Collaborators</h3>
			</div>
		</br>
		</br>
			<% @users.each do |user| %>
				<ul class="thumbnails">
					<li class="span1.5">
			 			<div class="thumbnail">
		      			<%= gravatar_for user %>
						</div>
					</li>
					<div class = "span 6"> 
						<p><h4><%= user.name %></h4></p>
						<div id = "add_remove_button">
							<% if user == current_user %>
								<p>(This is you)</p>
						  	<% elsif Ownership.find_by_project_id_and_user_id(@project.id, user.id) %>
						  		<%= form_for(Ownership.find_by_project_id_and_user_id(@project.id, user.id), html: {method: :delete}) do |f| %>
								<%= f.submit "Remove", class: "btn btn-default" %>
								<% end %>
						  	<% else %>
								<%= form_for(user.ownerships.build(project_id: @project.id)) do |f| %>
								<div><%= f.hidden_field :project_id %></div>
								<div><%= f.hidden_field :user_id %></div>
								<%= f.submit "Add", class: "btn btn-success" %>
						  		<% end %>
						  	<% end %>
						</div>
					</div>
			    </ul>
			   <% end %>
			</div>			
		</div>
	</div>
	<div class = "span4">
		&nbsp;
	</div>
</div>
</html>

app/views/projects/edit.html.erb
<!DOCTYPE HTML>
<html lang="en">
<div class="container-fluid">
	<div class= "row-fluid" >
		</br>
		<div class = "span3">
			&nbsp;
		</div>
		<div class = "span6">
		</br>		
			<div class = "well">
				<div align = "center">		
					<%= twitter_bootstrap_form_for @project do |project| %>
						<%= project.inputs 'Project Brief' do %>
						</br>
						<%= project.text_area :brief, "__", :size => "40x15" %>
						<%= project.actions do %>
							<%= project.submit 'Save', :class => 'btn'%>
						<% end %>
						<% end %>
					<% end %>
				</div>
			</div>
		</div>
		<div class = "span3">
			&nbsp;
			<%= render 'shared/project_error_messages' %>
		</div>
	</div>
</div>
</html>

app/views/projects/new.html.erb
<!DOCTYPE html>
<html>
<div class = "container-fluid">
	</br>
	</br>
	<div class= "row-fluid" >
		<div class = "span4">
			&nbsp;
		</div>
	  	<div class = "span4">
			<div class = "well">
				<div align = "center">
      			<%= render 'shared/project_form' %>
				</div>
			</div>
	  	</div>
      	<div class = "span4">
			<%= render 'shared/error_messages', object: @project %>
      	</div>
  	</div>
</div>
</html>

app/views/projects/show.html.erb
<!DOCTYPE html>
<%= javascript_include_tag('jquery.masonry.min') %>
<%= javascript_include_tag('jquery.imagesloaded.js') %>
<script>
$(document).ready(function() {
    var $container = $('#masonrybox');
    $container.imagesLoaded(function(){
        $container.masonry({
            itemSelector : '.scratch',
        });
    });
});
</script>
<html lang="en">
<div class = "container-fluid">
	<br>
	<div class = "row-fluid">
		<div class = "span2">
			&nbsp;
		</div>
		<div class = "span8"><div class = "page-header"><div align = "center">
		<h2><%= @project.title %></h2>
		<%= @project.body %>&nbsp;&nbsp;<%= link_to "Manage Collaborators", collaborators_project_path(@project),  %>
		</div></div></div>
		<div class = "span2">
			&nbsp;
		</div>
	</div>
	<div class = "row-fluid">
		<div class = "span12">
			<h3>Scratches</h3>
				<% unless @project.thoughts.empty? %>
					<%= link_to "+", new_project_thought_path(@project), :class => "btn btn-mini btn-success" %>
					</br>
					</br>
					<div id = "masonrybox">
						<%= render @thoughts %>
					</div>
				<% else %>
					</br>
					<blockquote>
						<em>No scratches yet. Add one now!</em>
					</blockquote>
					<%= link_to '+', new_project_thought_path(@project), :class => "btn btn-mini btn-success" %>
				<% end %>
		</div>
			</br>
	</div>
	<div class = "row-fluid">
		<div class = "span1">
			&nbsp;
		</div>
	</div>
	<div class = "row-fluid">
		<div class = "span5">
			<h3>Brief</h3>
			</br>
			<% if @project.brief.blank? %>
				<blockquote>
					<em>No brief yet</em>
				</blockquote>
				<%= link_to "+", edit_project_path(@project), :class => "btn btn-mini btn-success" %>
			<% else %>
				<blockquote>
					<%= @project.brief %> &nbsp;
					<%= link_to "edit", edit_project_path(@project) %>
				</blockquote>
			<% end %>
		</div>
		<div class = "span1">
			&nbsp;
		</div>
		<div class = "span4">
		<h3>Stories</strong></h3>
		</br>
		<% if @project.stories.empty? %>
			<blockquote>
				<em>No stories yet</em>
			</blockquote>
		<% else %>
			<%= render @stories %>
		<% end %>
		<%= link_to "+", new_project_story_path(@project), :class => "btn btn-mini btn-success" %>
		</br>
		</br>
		</div>
		<div class = "span1">
			&nbsp;
		</div>
	</div>
</div>
</html>