config/routes.rb
PmApp31::Application.routes.draw do
  get "sessions/new"

  resources :users, :only => [:new, :create, :show, :edit, :update]
  resources :sessions, :only => [:new, :create, :destroy]
  resources :ownerships, :only => [:create, :destroy]
  resources :projects do 
    member do
      get 'collaborators'
    end
    resources :stories
    resources :thoughts do
      resources :comments
    end
  end
  
  match '/getstarted',     :to => 'users#new'
  match '/signin',         :to => 'sessions#new'
  match '/signout',        :to => 'sessions#destroy'      
  match '/about',          :to => 'pages#about'
  
  root :to => 'pages#home'
  
end

app/models/story.rb
class Story < ActiveRecord::Base
  attr_accessible :content, :points, :user_id, :status, :type
  belongs_to :project
  
  default_scope :order => 'stories.created_at DESC'
  
  validates :project_id, :presence => true
  validates :content, :presence => true
end

app/controllers/stories_controller.rb
class StoriesController < ApplicationController
  before_filter :authenticate

  def new
    @project = Project.find(params[:project_id])
    @story = Story.new if signed_in?
    @title = "New story | Scratchboard"
  end
  
  def create
    @project = Project.find(params[:project_id])
    @story = @project.stories.build(params[:story])
    if @story.save
      redirect_to @project 
    else
      render 'new'
    end
  end
  
  def show
    @project = Project.find(params[:project_id])
    @story = Story.find(params[:id])
    if Ownership.find_by_project_id_and_user_id(@project.id, current_user.id)
      @story
    else
      redirect_to current_user
      flash[:"alert alert-warning"] = "Sorry - you do not have access to that story"
    end
  end
  
  def edit
    @project = Project.find(params[:project_id])
    @story = Story.find(params[:id])
    if Ownership.find_by_project_id_and_user_id(@project.id, current_user.id)
      edit_project_story_path(@project.id, @story.id)
    else
      redirect_to current_user
      flash[:"alert alert-warning"] = "Sorry - you do not have access to that story"
    end
  end
  
  def update
    @project = Project.find(params[:project_id])
    @story = Story.find(params[:id])
    if @story.update_attributes(params[:story])
      redirect_to @project
      flash[:"alert alert-success"] = "Story updated"
    else
      redirect_to @project
      flash[:"alert alert-warning"] = "Sorry - there was a problem saving your edit"
    end
  end
    
  def destroy
    @project = Project.find(params[:project_id])
    @story = Story.find(params[:id])
    @story.destroy
    redirect_to @project
    flash[:"alert alert-success"] = "Story deleted!"
  end  
     
end

app/views/stories/_story.html.erb
<!DOCTYPE html>
<html>
	<blockquote>
	<%= story.content %> &nbsp;  
	<%= link_to "edit", edit_project_story_path(@project.id, story.id) %>
	</blockquote>
</html>

app/views/stories/edit.html.erb
<!DOCTYPE HTML>
<html lang="en">
<div class="container-fluid">
	<div class= "row-fluid" >
		</br>
		<div class = "span3">
			&nbsp;
		</div>
		<div class = "span6">
		</br>		
			<div class = "well">
				<div align = "center">		
					<%= twitter_bootstrap_form_for [@project, @story], do |s| %>
						<%= s.inputs 'Edit Story' do %>
						</br>
						<%= s.text_area :content, "__", :size => "20x4" %>
						<%= s.actions do %>
							<%= s.submit 'Save', :class => 'btn'%>
						<% end %>
						<% end %>
					<% end %>
				</div>
				<div align = "right">
					<%= link_to 'delete', project_story_path(@project.id, @story.id), 
					:method => :delete, :confirm => "Are you sure you want to delete this story?" %>
				</div>
			</div>
		</div>
		<div class = "span3">
			&nbsp;
		</div>
	</div>
</div>
</html>

app/views/stories/new.html.erb
<!DOCTYPE html>
<html>
<div class = "container-fluid">
	</br>
	</br>
	<div class= "row-fluid" >
		<div class = "span4">
			&nbsp;
		</div>
	  	<div class = "span4">
			<div class = "well">
				<div align = "center">
      			<%= render 'shared/story_form' %>
				</div>
			</div>
	  	</div>
      	<div class = "span4">
			<%= render 'shared/error_messages', object: @story %>
      	</div>
  	</div>
</div>
</html>