config/routes.rb
PmApp31::Application.routes.draw do
  get "sessions/new"

  resources :users, :only => [:new, :create, :show, :edit, :update]
  resources :sessions, :only => [:new, :create, :destroy]
  resources :ownerships, :only => [:create, :destroy]
  resources :projects do 
    member do
      get 'collaborators'
    end
    resources :stories
    resources :thoughts do
      resources :comments
    end
  end
  
  match '/getstarted',     :to => 'users#new'
  match '/signin',         :to => 'sessions#new'
  match '/signout',        :to => 'sessions#destroy'      
  match '/about',          :to => 'pages#about'
  
  root :to => 'pages#home'
  
end

app/views/layouts/_footer.html.erb
<!DOCTYPE html>
<html lang="en">
<div class = "container-fluid">
	</br>
	</br>
	</br>
	</br>
</div>
</html>

app/views/layouts/_header.html.erb
<!DOCTYPE html>
<html lang="en">
<div class = "row">
    </br>
	</br>
	<div class = "span5">
		<% if signed_in? %>
			<%= link_to logo, current_user %>
		<% else %>
		    <%= link_to logo, root_path %>
		<% end %>
	</div>
	<% if signed_in? %>
		<div class = "span4">
			&nbsp;
		</div>
		<div class = "span3">
			</br>
			<div class="btn-group">
			  <a class="btn dropdown-toggle" data-toggle="dropdown" href= '#'>
				<i class="icon-user"></i>
				<%= current_user.name %>
			    <span class="caret"></span>
			  </a>
			  <ul class="dropdown-menu">
			    <%= link_to "Projects", current_user %>
				<%= link_to "Edit Profile", edit_user_path(current_user) %>
				<li class="divider"></li>
				<%= link_to "About", '/about' %>
				<li class="divider"></li>
				<%= link_to "Log Out", signout_path %>
			  </ul>
		</div>
	<% else %>
		<div class = "span5">
			&nbsp;
		</div>
		<div class = "span2">
			</br>
			<a class = 'btn' href = '/signin'><i class="icon-lock"></i> Login</a>
		</div>
	<% end %>
</br>
</div>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
	<%= favicon_link_tag %>
    <title><%= title %></title>
    <%= stylesheet_link_tag    "application", media: "all" %>
	<%= javascript_include_tag "application" %>
	<%= csrf_meta_tag %>
  </head>
  <body>
	<div class="container">
		<%= render 'layouts/header' %>
		<div class = "container">
			<% flash.each do |key, value| %>
		    	<div class="alert alert-<%= key %>"><%= value %></div>
			<% end %>
		</div>
    	<%= yield %>
		<%= render 'layouts/footer' %>
  	</div>
  </body>
</html>